### ISSUE TITLE
Unittest fails to compile on ubuntu 18.04

### ISSUE THREAD

**Issue by Akilesh1597** [aws/aws-sdk-cpp#1634]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I have compiled the sdk according to instructions from README and also installed the same. 
When compiling the dynamodb application I had written I hit the below failure. 
```
/usr/bin/ld: /tmp/ccN8s81j.o: undefined reference to symbol '_ZN3Aws3Crt11g_allocatorE'
```

**SDK version number**
bccf0f2838ee2483aaea60113e7963770894a646  (tag 1.9.8)

**Platform/OS/Hardware/Device**
Ubuntu 18.04
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
cmake version 3.10.2
libssl1.1.1-1ubuntu2.1~18.04.9
libcurl4-openssl-dev 7.58.0-2ubuntu3.13

**To Reproduce (observed behavior)**
I will share the code after sanitizing it 

**Expected behavior**
All tests for the shared library that I am building passes. 

**Logs/output**
```
/usr/bin/gcc ./unittests/QueryDynamoTests.cpp -I. -g -Wall -L . -lquerydynamo -laws-cpp-sdk-core -laws-cpp-sdk-dynamodb -lgtest -lpthread -lstdc++ -o unittests/QueryDynamoTests.exe
/usr/bin/ld: /tmp/ccN8s81j.o: undefined reference to symbol '_ZN3Aws3Crt11g_allocatorE'
/usr/local/lib/libaws-crt-cpp.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:26: recipe for target 'unittests/QueryDynamoTests.exe' failed
make: *** [unittests/QueryDynamoTests.exe] Error 1
```

**Additional context**
This started occuring only after building and installing the sdk from 'main' branch today.

**Comment by Akilesh1597** [comment]
Adding '-laws-crt-cpp -laws-c-common' causes a core dump.

**Comment by KaibaLopez** [comment]
Hi @Akilesh1597 ,
I'm going to need to see the unit tests you're trying to run, otherwise the only thing I can think of is that you're trying to use some sdk symbols before having initialized the sdk with the `Aws::InitAPI()` call. 
Ah and yea you shouldn't need to add laws-crt-cpp or c-common, so don't worry about those.
