### ISSUE TITLE
Failed to build with OpenSSL 1.1

### ISSUE THREAD

**Issue by 0x1997** [aws/aws-sdk-cpp#361]
OS: Debian testing
arch: amd64
gcc: 6.1.1
libssl-dev: 1.1.0c-2
aws-sdk: 1.0.37

```shell
[45/303] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/crypto/openssl/CryptoImpl.cpp.o
FAILED: aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/crypto/openssl/CryptoImpl.cpp.o 
/usr/bin/c++   -DENABLE_CURL_CLIENT -DENABLE_OPENSSL_ENCRYPTION -DPLATFORM_LINUX -Daws_cpp_sdk_core_EXPORTS -I../aws-cpp-sdk-core/include -I../aws-cpp-sdk-core/include/aws/core/platform/refs -Wall -Werror -pedantic -Wextra -fno-exceptions -O3 -DNDEBUG -fPIC   -std=c++17 -MD -MT aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/crypto/openssl/CryptoImpl.cpp.o -MF aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/crypto/openssl/CryptoImpl.cpp.o.d -o aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/crypto/openssl/CryptoImpl.cpp.o -c ../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp
In file included from ../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:18:0:
../aws-cpp-sdk-core/include/aws/core/utils/crypto/openssl/CryptoImpl.h:194:32: error: field 'm_ctx' has incomplete type 'EVP_CIPHER_CTX {aka evp_cipher_ctx_st}'
                 EVP_CIPHER_CTX m_ctx;
                                ^~~~~
In file included from ../aws-cpp-sdk-core/include/aws/core/utils/crypto/openssl/CryptoImpl.h:22:0,
                 from ../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:18:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of 'EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}'
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^~~~~~~~~~~~~~~~~
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp: In function 'void Aws::Utils::Crypto::OpenSSL::cleanup_static_state()':
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:65:55: error: the address of 'void Aws::Utils::Crypto::OpenSSL::locking_fn(int, int, const char*, int)' will never be NULL [-Werror=address]
                     if (CRYPTO_get_locking_callback() == &locking_fn)
                                                       ^
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:73:50: error: the address of 'long unsigned int Aws::Utils::Crypto::OpenSSL::id_fn()' will never be NULL [-Werror=address]
                     if (CRYPTO_get_id_callback() == &id_fn)
                                                  ^
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp: In member function 'virtual Aws::Utils::Crypto::HashResult Aws::Utils::Crypto::Sha256HMACOpenSSLImpl::Calculate(const ByteBuffer&, const ByteBuffer&)':
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:207:26: error: aggregate 'HMAC_CTX ctx' has incomplete type and cannot be defined
                 HMAC_CTX ctx;
                          ^~~
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:208:35: error: 'HMAC_CTX_init' was not declared in this scope
                 HMAC_CTX_init(&ctx);
                                   ^
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:214:38: error: 'HMAC_CTX_cleanup' was not declared in this scope
                 HMAC_CTX_cleanup(&ctx);
                                      ^
cc1plus: all warnings being treated as errors
```

**Comment by bretambrose** [comment]
Another user has submitted a pull request to address this.  We will evaluate that PR and update this when it gets merged in.
