### ISSUE TITLE
[Gcc 11.2.0] Does not compile with gcc 11.2.0

### ISSUE THREAD

**Issue by zolt4n** [aws/aws-sdk-cpp#1795]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Does not build with gcc 11.2.0

**SDK version number**
Same error on : 
 - 1.9.39
 - 1.9.120

**Platform/OS/Hardware/Device**
redhat 7

**To Reproduce (observed behavior)**

cmake/3.20.2/bin/cmake \
        -DCMAKE_AR:STRING="${AR}" \
        -DCMAKE_BUILD_TYPE:STRING=Release \
        -DCMAKE_CXX_COMPILER:STRING="${CXX}" \
        -DCMAKE_C_FLAGS="${CFLAGS} ${PIC_FLAG} "\
        -DCMAKE_CXX_FLAGS="${CXXFLAGS} ${PIC_FLAG} "\
        -DCMAKE_INSTALL_PREFIX:PATH="${PREFIX_DEST}" \
        -DCMAKE_RANLIB:STRING="${RANLIB}" \
        -DCUSTOM_MEMORY_MANAGEMENT=OFF \
        -DENABLE_UNITY_BUILD=ON \
        -DBUILD_SHARED_LIBS=OFF \
        -DCPP_STANDARD=2a \
        -DOPENSSL_ROOT_DIR="${DEST}/openssl/1.1.1k/${COMPILER_TUPLE}${PREFIX}" \
        -DENABLE_TESTING=OFF \
        -DBUILD_ONLY="s3;s3-crt;transfer" \
        -DZLIB_ROOT="${DEST}/zlib/1.2.11/${COMPILER_TUPLE}${PREFIX}" \
        -DUSE_OPENSSL=ON \
        -S . -B _build

**Expected behavior**

building :)

**Logs/output**

So I see 2 errors : 

1. warning based one : 
```gcc
export/home/scratch/bbordet2/work/aws-sdk-cpp-1.9.39/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.c:92:44: error: argument 1 of type ‘int16_t[256]’ {aka ‘short int[256]’} with mismatched bound [-Werror=array-parameter=]
   92 | void PQCLEAN_KYBER51290S_CLEAN_ntt(int16_t poly[256]) {
      |                                    ~~~~~~~~^~~~~~~~~
In file included from /export/home/scratch/bbordet2/work/aws-sdk-cpp-1.9.39/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.c:1:
/export/home/scratch/bbordet2/work/aws-sdk-cpp-1.9.39/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.h:9:45: note: previously declared as ‘int16_t *’ {aka ‘short int *’}
    9 | void PQCLEAN_KYBER51290S_CLEAN_ntt(int16_t *poly);
      |                                    ~~~~~~~~~^~~~
/export/home/scratch/bbordet2/work/aws-sdk-cpp-1.9.39/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.c:116:47: error: argument 1 of type ‘int16_t[256]’ {aka ‘short int[256]’} with mismatched bound [-Werror=array-parameter=]
  116 | void PQCLEAN_KYBER51290S_CLEAN_invntt(int16_t poly[256]) {
      |                                       ~~~~~~~~^~~~~~~~~
In file included from /export/home/scratch/bbordet2/work/aws-sdk-cpp-1.9.39/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.c:1:
/export/home/scratch/bbordet2/work/aws-sdk-cpp-1.9.39/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.h:10:48: note: previously declared as ‘int16_t *’ {aka ‘short int *’}
   10 | void PQCLEAN_KYBER51290S_CLEAN_invntt(int16_t *poly);
      |                                       ~~~~~~~~~^~~~
[ 27%] Building C object crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/kyber_r2/indcpa.c.o
[ 27%] Building C object crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/kyber_r2/kyber_r2_kem.c.o
[ 28%] Building C object crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/kyber_r2/ntt.c.o
cc1: all warnings being treated as errors
[ 28%] Building C object crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/kyber_r2/poly.c.o
gmake[2]: *** [crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/kyber_90s_r2/ntt.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
[ 28%] Building C object crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/kyber_r2/polyvec.c.o
/export/home/scratch/bbordet2/work/aws-sdk-cpp-1.9.39/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_r2/ntt.c:92:41: error: argument 1 of type ‘int16_t[256]’ {aka ‘short int[256]’} with mismatched bound [-Werror=array-parameter=]
   92 | void PQCLEAN_KYBER512_CLEAN_ntt(int16_t poly[256]) {
      |                                 ~~~~~~~~^~~~~~~~~
In file included from /export/home/scratch/bbordet2/work/aws-sdk-cpp-1.9.39/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_r2/ntt.c:1:
/export/home/scratch/bbordet2/work/aws-sdk-cpp-1.9.39/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_r2/ntt.h:9:42: note: previously declared as ‘int16_t *’ {aka ‘short int *’}
    9 | void PQCLEAN_KYBER512_CLEAN_ntt(int16_t *poly);
      |                                 ~~~~~~~~~^~~~
/export/home/scratch/bbordet2/work/aws-sdk-cpp-1.9.39/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_r2/ntt.c:116:44: error: argument 1 of type ‘int16_t[256]’ {aka ‘short int[256]’} with mismatched bound [-Werror=array-parameter=]
  116 | void PQCLEAN_KYBER512_CLEAN_invntt(int16_t poly[256]) {
      |                                    ~~~~~~~~^~~~~~~~~
In file included from /export/home/scratch/bbordet2/work/aws-sdk-cpp-1.9.39/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_r2/ntt.c:1:
/export/home/scratch/bbordet2/work/aws-sdk-cpp-1.9.39/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_r2/ntt.h:10:45: note: previously declared as ‘int16_t *’ {aka ‘short int *’}
   10 | void PQCLEAN_KYBER512_CLEAN_invntt(int16_t *poly);
      |                                    ~~~~~~~~~^~~~
cc1: all warnings being treated as errors
``` 

2. operant type mismatch.

```

[ 31%] Linking C static library libaws-checksums.a
[ 31%] Linking C static library libaws-c-compression.a
[ 31%] Built target aws-checksums
[ 31%] Built target aws-c-compression
/tmp/ccSNVpkm.s: Assembler messages:
/tmp/ccSNVpkm.s:21: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:25: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:29: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:47: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:60: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:61: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:65: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:66: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:75: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:79: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:103: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:104: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:133: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:136: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:142: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:143: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:149: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:150: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:159: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:162: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:209: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:213: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:222: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:226: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:230: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:241: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:244: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:304: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccSNVpkm.s:305: Error: operand type mismatch for `vpclmulqdq'
gmake[2]: *** [crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/bike_r3/gf2x_mul_base_vpclmul.c.o] Error 1

```

**Additional context**
N/A

**Comment by chubin** [comment]
Ok, I managed to build it. The main problem was that I used `prefetch_crt_dependency.sh` to fetch the dependencies (as recommended in #1811). This script seems to fetch outdated dependencies though. If you fetch the actual dependencies with `git clone --recurive`, the problems (there were more than this one) disappear

**Comment by KaibaLopez** [comment]
Hi @zolt4n ,
This has been fixed on the CRT side, let me know if you still have this problem but otherwise I believe I'll be closing it.

**Comment by starrocks-xueli** [comment]
I am having the same problem in GCC 10.3.0, using the latest code, maybe the fix is not right?

```
(main) code/aws-sdk-cpp/build ➜ make
[  9%] Built target aws-c-common
[ 10%] Built target aws-c-compression
Consolidate compiler generated dependencies of target s2n
[ 10%] Building C object crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/bike_r3/gf2x_mul_base_vpclmul.c.o
/tmp/cc0u5SWz.s: Assembler messages:
/tmp/cc0u5SWz.s:74: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc0u5SWz.s:102: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc0u5SWz.s:221: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc0u5SWz.s:439: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc0u5SWz.s:448: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc0u5SWz.s:481: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc0u5SWz.s:516: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc0u5SWz.s:610: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc0u5SWz.s:641: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc0u5SWz.s:1255: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc0u5SWz.s:1264: Error: operand type mismatch for `vpclmulqdq'
make[2]: *** [crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/bike_r3/gf2x_mul_base_vpclmul.c.o] Error 1
make[1]: *** [crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/all] Error 2
make: *** [all] Error 2

**Comment by chubin** [comment]
I believe, the real reason was not the compiler, but glibc

-- 
Igor Chubin

**Comment by starrocks-xueli** [comment]
using GCC 10.3.0, `make` can not succeed, time: 2021-12-15.


```
git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp
cd aws-sdk-cpp
mkdir build
cd build
cmake .. -DBUILD_ONLY="s3;s3-crt;transfer" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=ON
make
```

```
(main) code/aws-sdk-cpp/build ➜ make
Consolidate compiler generated dependencies of target aws-c-common
[  9%] Built target aws-c-common
Consolidate compiler generated dependencies of target aws-c-compression
[ 10%] Built target aws-c-compression
Consolidate compiler generated dependencies of target s2n
[ 10%] Building C object crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/bike_r3/gf2x_mul_base_vpclmul.c.o
/tmp/ccXzFXGQ.s: Assembler messages:
/tmp/ccXzFXGQ.s:74: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccXzFXGQ.s:102: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccXzFXGQ.s:221: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccXzFXGQ.s:439: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccXzFXGQ.s:448: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccXzFXGQ.s:481: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccXzFXGQ.s:516: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccXzFXGQ.s:610: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccXzFXGQ.s:641: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccXzFXGQ.s:1255: Error: operand type mismatch for `vpclmulqdq'
/tmp/ccXzFXGQ.s:1264: Error: operand type mismatch for `vpclmulqdq'
make[2]: *** [crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/bike_r3/gf2x_mul_base_vpclmul.c.o] Error 1
make[1]: *** [crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/all] Error 2
make: *** [all] Error 2
```

@KaibaLopez
