### PR TITLE
Fix #361 adding conditions to differentiate OpenSSL v1.0.2 and v1.1.x in CryptoImpl

### LINKED ISSUE #361: Failed to build with OpenSSL 1.1
OS: Debian testing
arch: amd64
gcc: 6.1.1
libssl-dev: 1.1.0c-2
aws-sdk: 1.0.37

```shell
[45/303] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/crypto/openssl/CryptoImpl.cpp.o
FAILED: aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/crypto/openssl/CryptoImpl.cpp.o 
/usr/bin/c++   -DENABLE_CURL_CLIENT -DENABLE_OPENSSL_ENCRYPTION -DPLATFORM_LINUX -Daws_cpp_sdk_core_EXPORTS -I../aws-cpp-sdk-core/include -I../aws-cpp-sdk-core/include/aws/core/platform/refs -Wall -Werror -pedantic -Wextra -fno-exceptions -O3 -DNDEBUG -fPIC   -std=c++17 -MD -MT aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/crypto/openssl/CryptoImpl.cpp.o -MF aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/crypto/openssl/CryptoImpl.cpp.o.d -o aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/crypto/openssl/CryptoImpl.cpp.o -c ../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp
In file included from ../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:18:0:
../aws-cpp-sdk-core/include/aws/core/utils/crypto/openssl/CryptoImpl.h:194:32: error: field 'm_ctx' has incomplete type 'EVP_CIPHER_CTX {aka evp_cipher_ctx_st}'
                 EVP_CIPHER_CTX m_ctx;
                                ^~~~~
In file included from ../aws-cpp-sdk-core/include/aws/core/utils/crypto/openssl/CryptoImpl.h:22:0,
                 from ../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:18:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of 'EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}'
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^~~~~~~~~~~~~~~~~
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp: In function 'void Aws::Utils::Crypto::OpenSSL::cleanup_static_state()':
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:65:55: error: the address of 'void Aws::Utils::Crypto::OpenSSL::locking_fn(int, int, const char*, int)' will never be NULL [-Werror=address]
                     if (CRYPTO_get_locking_callback() == &locking_fn)
                                                       ^
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:73:50: error: the address of 'long unsigned int Aws::Utils::Crypto::OpenSSL::id_fn()' will never be NULL [-Werror=address]
                     if (CRYPTO_get_id_callback() == &id_fn)
                                                  ^
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp: In member function 'virtual Aws::Utils::Crypto::HashResult Aws::Utils::Crypto::Sha256HMACOpenSSLImpl::Calculate(const ByteBuffer&, const ByteBuffer&)':
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:207:26: error: aggregate 'HMAC_CTX ctx' has incomplete type and cannot be defined
                 HMAC_CTX ctx;
                          ^~~
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:208:35: error: 'HMAC_CTX_init' was not declared in this scope
                 HMAC_CTX_init(&ctx);
                                   ^
../aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:214:38: error: 'HMAC_CTX_cleanup' was not declared in this scope
                 HMAC_CTX_cleanup(&ctx);
                                      ^
cc1plus: all warnings being treated as errors
```

### PR DESCRIPTION
**Pull request by jliang1010**
OpenSSL v1.1 issue has been mentioned in both #361

### CODE REVIEW

**Comment by bretambrose** [comment]
I've pulled this into an internal repo where we can have our security team review it.  Thanks for doing this work.

File: aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp [hunk 1]
```diff
@@ -35,16 +35,19 @@ namespace Aws
         {
             namespace OpenSSL
             {
+#if OPENSSL_VERSION_NUMBER < 0x10100003L
```
Comment (bretambrose) [inline aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp]: I believe the version numbers should have a 1 (or a zero, doesn't really matter) as the last digit, so that people on 1.1b and 1.1a work as well.

File: aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp [hunk 2]
```diff
@@ -35,16 +35,19 @@ namespace Aws
...
 
+#endif
                 GetTheLights getTheLights;
 
                 void init_static_state()
                 {
                     ERR_load_CRYPTO_strings();
                     OPENSSL_add_all_algorithms_noconf();
 
+#if OPENSSL_VERSION_NUMBER < 0x10100003L
```
Comment (bretambrose) [inline aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp]: Why is the locking setup removed here?  Is there some documentation somewhere on why it's no longer necessary.  I can't find anything about it being deprecated.

**Comment by andred** [comment]
Any update on this? Is anything wrong with the patches?

**Comment by bretambrose** [comment]
We've got a lot on our plate at the moment so no one's had a chance to go through and test it thoroughly yet.

**Comment by andred** [comment]
Thanks for the update Bret.

**Comment by janekolszak** [comment]
What's up with this PR?

File: aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp [hunk 3]
```diff
@@ -204,14 +212,24 @@ namespace Aws
...
 
-                HMAC_CTX ctx;
-                HMAC_CTX_init(&ctx);
+                HMAC_CTX *ctx;
+#if OPENSSL_VERSION_NUMBER < 0x10100003L
+                HMAC_CTX _ctx;
+                ctx = &_ctx;
+                HMAC_CTX_init(ctx);
+#else
+                ctx=HMAC_CTX_new();
```
Comment (JonathanHenson) [inline aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp]: Why are we now allocating things on the heap? Is this required for the latest OpenSSL?

File: aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp [hunk 4]
```diff
@@ -238,10 +256,7 @@ namespace Aws
             OpenSSLCipher::OpenSSLCipher(OpenSSLCipher&& toMove) : SymmetricCipher(std::move(toMove)),
                                                                    m_encDecInitialized(false)
             {
-                m_ctx = toMove.m_ctx;
-                toMove.m_ctx.cipher = nullptr;
-                toMove.m_ctx.cipher_data = nullptr;
-                toMove.m_ctx.engine = nullptr;
+                EVP_CIPHER_CTX_copy(m_ctx, toMove.m_ctx);
```
Comment (JonathanHenson) [inline aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp]: I like this change!

File: aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp [hunk 5]
```diff
@@ -271,7 +286,13 @@ namespace Aws
 
             void OpenSSLCipher::Init()
             {
-                EVP_CIPHER_CTX_init(&m_ctx);
+#if OPENSSL_VERSION_NUMBER < 0x10100003L
+                m_ctx = &_m_ctx;
+                EVP_CIPHER_CTX_init(m_ctx);
```
Comment (JonathanHenson) [inline aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp]: not sure why this is inside the compiletime ifdefs, isn't it the same between versions?

File: aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp (hunk 3 above)
Comment (andred) [inline aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp]: I believe so. Several structures have been made opaque in OpenSSL 1.1, so the OpenSSL allocators have to be used, see https://www.openssl.org/docs/man1.1.0/crypto/HMAC_CTX_free.html unless there is something I missed.

File: aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp (hunk 5 above)
Comment (andred) [inline aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp]: Thanks, well spotted. EVP_CIPHER_CTX_init() is obsolete in OpenSSL 1.1, and they
#  define EVP_CIPHER_CTX_init(c)      EVP_CIPHER_CTX_reset(c)
in evp.h
So the call should really be to EVP_CIPHER_CTX_reset() instead. Can you apply that change before merging, or do you want me to update the commit?

File: aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp [hunk 6]
```diff
@@ -271,7 +286,13 @@ namespace Aws
...
+#else
+                m_ctx = EVP_CIPHER_CTX_new();
```
Comment (JonathanHenson) [inline aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp]: Uggh, I just tried to make this not need all the #ifdef checks until I realized the *new and *free functions where not part of the 1.0 interface. I'll be merging this. 

In the meantime the new and free needs to be moved to constructor and destructors, then I'll merge it over.

File: aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp (hunk 4 above)
Comment (andred) [inline aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp]: This actually needs updating, as m_ctx hasn't been assigned yet. I believe a call to init() should be sufficient.

**Comment by singku** [comment]
I am closing this PR because it's similar with https://github.com/aws/aws-sdk-cpp/pull/507
