### ISSUE TITLE
Debian Jessie 8 - build failure due to openssl version

### ISSUE THREAD

**Issue by artsera** [aws/aws-sdk-cpp#877]
### Can you provide a TRACE level log? (sanitize any sensitive information)No

Link was failing with complaints about missing public symbols from the SSL libraries.  Jessie 8 comes with libssl.so and crypto.so as symbolic links to libssl.so.1.0.0 and libcrypto.so.1.0.0 in the directory /usr/lib/x86_64-linux-gnu.

What is needed is openssl version 1.1 instead of version 1.0. On my system, the 1.1 version is also located in the above mentioned directory.  I reset the symbolic links to point to the version 1.1 variants and then restarted the make after a make clean.  This worked and the build completed successfully.

**Comment by singku** [comment]
Could you please let us know which symbols are missing? We have compiled our SDK against openssl 1.0.2g

**Comment by artsera** [comment]
Below is the result of running the make when 
'/usr/lib/x86_64-linux-gnu/libssl.so' is a symbolic link to 
'/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0' and
'/usr/lib/x86_64-linux-gnu/libcrypto.so' is a symbolic link to 
'/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0'.

*** output from make ***
/usr/bin/g++-5      -rdynamic 
@CMakeFiles/aws-cpp-sdk-cognitoidentity-integration-tests.dir/objects1.rsp 
-o aws-cpp-sdk-cognitoidentity-integration-tests 
-Wl,-rpath,/local2/src/public/aws-sdk-cpp-master/bld/aws-cpp-sdk-access-management:/local2/src/public/aws-sdk-cpp-master/bld/aws-cpp-sdk-cognito-identity:/local2/src/public/aws-sdk-cpp-master/bld/aws-cpp-sdk-iam:/local2/src/public/aws-sdk-cpp-master/bld/testing-resources:/local2/src/public/aws-sdk-cpp-master/bld/aws-cpp-sdk-core:/usr/local/lib 
../aws-cpp-sdk-access-management/libaws-cpp-sdk-access-management.so 
../aws-cpp-sdk-cognito-identity/libaws-cpp-sdk-cognito-identity.so 
../aws-cpp-sdk-iam/libaws-cpp-sdk-iam.so 
../testing-resources/libtesting-resources.so 
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so -lpthread -lcurl -lssl 
-lcrypto /usr/local/lib/libz.so
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`HMAC_CTX_reset'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`OPENSSL_init_crypto'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`EVP_CIPHER_CTX_reset'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`HMAC_CTX_free'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`EVP_MD_CTX_new'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`EVP_MD_CTX_free'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`HMAC_CTX_new'
collect2: error: ld returned 1 exit status
aws-cpp-sdk-cognitoidentity-integration-tests/CMakeFiles/aws-cpp-sdk-cognitoidentity-integration-tests.dir/build.make:110: 
recipe for target 
'aws-cpp-sdk-cognitoidentity-integration-tests/aws-cpp-sdk-cognitoidentity-integration-tests' 
failed

---------------------------------------------

I will reset to version 1.0.2 and send you the results.

Arthur


Andrew Tang wrote:

**Comment by artsera** [comment]
Hi,

I sent you the results when I used ssl version 1.0.0.  Here are the 
results from trying to build with ssl version 1.0.2.  I don't know if 
that is the same as 1.0.2g since the naming convention does not include 
the g.  Obviously, the lack of using the g could mean that it is not 
1.0.2g, or that they just don't include the g in their naming conventions.

Here is the result of the build failure when using ssl 1.0.2:

cd 
/local2/src/public/aws-sdk-cpp-master/bld/aws-cpp-sdk-cognitoidentity-integration-tests 
&& /usr/bin/cmake -E cmake_link_script 
CMakeFiles/aws-cpp-sdk-cognitoidentity-integration-tests.dir/link.txt 
--verbose=1
/usr/bin/g++-5      -rdynamic 
@CMakeFiles/aws-cpp-sdk-cognitoidentity-integration-tests.dir/objects1.rsp 
-o aws-cpp-sdk-cognitoidentity-integration-tests 
-Wl,-rpath,/local2/src/public/aws-sdk-cpp-master/bld/aws-cpp-sdk-access-management:/local2/src/public/aws-sdk-cpp-master/bld/aws-cpp-sdk-cognito-identity:/local2/src/public/aws-sdk-cpp-master/bld/aws-cpp-sdk-iam:/local2/src/public/aws-sdk-cpp-master/bld/testing-resources:/local2/src/public/aws-sdk-cpp-master/bld/aws-cpp-sdk-core:/usr/local/lib 
../aws-cpp-sdk-access-management/libaws-cpp-sdk-access-management.so 
../aws-cpp-sdk-cognito-identity/libaws-cpp-sdk-cognito-identity.so 
../aws-cpp-sdk-iam/libaws-cpp-sdk-iam.so 
../testing-resources/libtesting-resources.so 
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so -lpthread -lcurl -lssl 
-lcrypto /usr/local/lib/libz.so
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`HMAC_CTX_reset'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`OPENSSL_init_crypto'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`EVP_CIPHER_CTX_reset'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`HMAC_CTX_free'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`EVP_MD_CTX_new'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`EVP_MD_CTX_free'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to 
`HMAC_CTX_new'
collect2: error: ld returned 1 exit status
aws-cpp-sdk-cognitoidentity-integration-tests/CMakeFiles/aws-cpp-sdk-cognitoidentity-integration-tests.dir/build.make:110: 
recipe for target 
'aws-cpp-sdk-cognitoidentity-integration-tests/aws-cpp-sdk-cognitoidentity-integration-tests' 
failed


--------------------------------------------------

It does complete successfully when the openssl version for 'libssl' and 
'libcrypto' is 1.1.  There are some problems with 'libcurl' that 
required updating that lib before it finally worked.

Thanks,

Arthur Sera

Andrew Tang wrote:

**Comment by singku** [comment]
What's your sdk version then? In latest SDK,  those symbols are only used against openssl 1.1.

**Comment by KaibaLopez** [comment]
Hi @artsera ,
sorry for the lack of responses, I'm going through old issues and wanted to know if you're still facing problems with this??
