### ISSUE TITLE
0.9.6 Build fails on OSX Mavericks

### ISSUE THREAD

**Issue by zwass** [aws/aws-sdk-cpp#141]
We found this problem while trying to get the SDK added to Homebrew for easy installation on OSX.

See https://github.com/Homebrew/homebrew/pull/50360

```
CPU: quad-core 64-bit ivybridge
OS X: 10.9.5-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_73
```

```
[ 69%] Building CXX object aws-cpp-sdk-autoscaling/CMakeFiles/aws-cpp-sdk-autoscaling.dir/source/model/DescribeScheduledActionsResult.cpp.o
cd /tmp/aws-sdk-cpp20160329-47947-1x5grlx/aws-sdk-cpp-0.9.6/build/aws-cpp-sdk-autoscaling && /usr/local/Library/ENV/4.3/clang++   -DAWS_SDK_PLATFORM_APPLE -DENABLE_COMMONCRYPTO_ENCRYPTION -DENABLE_CURL_CLIENT -DJSON_USE_EXCEPTION=0 -Daws_cpp_sdk_autoscaling_EXPORTS -I/tmp/aws-sdk-cpp20160329-47947-1x5grlx/aws-sdk-cpp-0.9.6/aws-cpp-sdk-autoscaling/include -I/tmp/aws-sdk-cpp20160329-47947-1x5grlx/aws-sdk-cpp-0.9.6/aws-cpp-sdk-core/include  -std=c++11 -fno-exceptions -Wall -Werror -Wno-unused-private-field -Wno-comment -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/aws-cpp-sdk-autoscaling.dir/source/model/DescribeScheduledActionsResult.cpp.o -c /tmp/aws-sdk-cpp20160329-47947-1x5grlx/aws-sdk-cpp-0.9.6/aws-cpp-sdk-autoscaling/source/model/DescribeScheduledActionsResult.cpp
/tmp/aws-sdk-cpp20160329-47947-1x5grlx/aws-sdk-cpp-0.9.6/aws-cpp-sdk-transfer/source/transfer/UploadFileRequest.cpp:117:63: error: chosen constructor is explicit in copy-initialization
UploadFileRequest(fileName, bucketName, keyName, contentType, {}, s3Client, createBucket, doConsistencyChecks)
                                                              ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
/tmp/aws-sdk-cpp20160329-47947-1x5grlx/aws-sdk-cpp-0.9.6/aws-cpp-sdk-transfer/source/transfer/UploadFileRequest.cpp:58:75: note: passing argument to parameter 'metadata' here
                                     Aws::Map<Aws::String, Aws::String>&& metadata,
```

[Full console output](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/43855/version=mavericks/consoleFull)

**Comment by zwass** [comment]
I can also repro this with OSX 10.10 Yosemite and Clang 6.0.

**Comment by zwass** [comment]
I should note that building from HEAD works on 10.10 and Clang 6.0. I don't have any way to start up my own VM or physical machine on 10.9, so I have not been able to test there. Is it possible to tag a new release? The Homebrew folks really like to see packages built from tagged releases.

**Comment by JonathanHenson** [comment]
We can start tagging releases for you.
Do you need a new tag immediately before you can add this to homebrew?

**Comment by JonathanHenson** [comment]
As a side note. There will never be a push to this repo on the master branch that we haven't already built and tested on Apple platforms. We are still working out what the release tagging will look like and I'll keep you posted.

**Comment by zwass** [comment]
Thanks for checking in!

It looks like this error still occurs when building from HEAD, even on OSX 10.10/Clang 6.0 (I must have made a mistake earlier and not built the `transfer` client that has the offending code).

It doesn't seem to be something from the way that Homebrew tries to build, as I get the error when building directly from a fresh clone of the git repo:
```
$ clang --version
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
$ mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="transfer" ..
...omitted...
[ 90%] Building CXX object aws-cpp-sdk-transfer/CMakeFiles/aws-cpp-sdk-transfer.dir/source/transfer/UploadFileRequest.cpp.o
/Users/zwass/aws-sdk-cpp/aws-cpp-sdk-transfer/source/transfer/UploadFileRequest.cpp:117:63: error: 
      chosen constructor is explicit in copy-initialization
UploadFileRequest(fileName, bucketName, keyName, contentType, {}, s3Client, cr...
                                                              ^~
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/map:838:14: note: 
      constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
/Users/zwass/aws-sdk-cpp/aws-cpp-sdk-transfer/source/transfer/UploadFileRequest.cpp:58:75: note: 
      passing argument to parameter 'metadata' here
                                     Aws::Map<Aws::String, Aws::String>&& metadata,
                                                                          ^
1 error generated.
make[2]: *** [aws-cpp-sdk-transfer/CMakeFiles/aws-cpp-sdk-transfer.dir/source/transfer/UploadFileRequest.cpp.o] Error 1
make[1]: *** [aws-cpp-sdk-transfer/CMakeFiles/aws-cpp-sdk-transfer.dir/all] Error 2
make: *** [all] Error 2
```

Once we get this sorted, it would be great if we could tag a new version.

Thanks!

**Comment by JonathanHenson** [comment]
Something else is wrong, I just built every thing that n OS X and have been for months. Can I see your full cmake and build cli output?

**Comment by zwass** [comment]
Full output: https://gist.github.com/zwass/0d1d8a8667352ccf4912c64b93971d79

This is on a fresh install of 10.10 with `command_line_tools_for_osx_10.10_for_xcode_6.1.dmg` installed from the Apple developer site.

**Comment by zwass** [comment]
@JonathanHenson Please see my PR that fixes this error. It would be great if you could tag a new version once this is tested/merged.

**Comment by JonathanHenson** [comment]
I'll be merging in your PR shortly.

**Comment by JonathanHenson** [comment]
I've automated the tags on each release. I haven't added your updates yet.

**Comment by JonathanHenson** [comment]
I've updated this and tagged the release at 0.10.5. Could you have a look and reopen if the problem persists?
