### ISSUE TITLE
 "undefined reference" when building example

### ISSUE THREAD

**Issue by zcchai-iotex** [aws/aws-sdk-cpp#1230]
Hello,
I am working on Ubuntu 4.15.0-55 with the latest SDK.
I was building the sample code:
 https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/s3/put_object.cpp

However, there are errors as shown below.

Any ideas what's wrong with those steps?

Thanks
Zhenchuan

= == ===============

#mkdir BUILD_DIR
#cd BUILD_DIR
#cmake /path/to/root/of/sdk -DBUILD_ONLY="s3"
#make 
#make install

#g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
#g++ put_object.cpp
/tmp/cca4niF8.o: In function `put_s3_object(std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > const&)':
put_object.cpp:(.text+0x1ab): undefined reference to `Aws::Client::ClientConfiguration::ClientConfiguration()'
put_object.cpp:(.text+0x1fe): undefined reference to `Aws::S3::S3Client::S3Client(Aws::Client::ClientConfiguration const&, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy, bool)'
put_object.cpp:(.text+0x20d): undefined reference to `Aws::S3::Model::PutObjectRequest::PutObjectRequest()'
put_object.cpp:(.text+0x2ef): undefined reference to `Aws::S3::S3Client::PutObject(Aws::S3::Model::PutObjectRequest const&) const'
put_object.cpp:(.text+0x3f5): undefined reference to `Aws::S3::S3Client::~S3Client()'
put_object.cpp:(.text+0x480): undefined reference to `Aws::S3::S3Client::~S3Client()'
/tmp/cca4niF8.o: In function `main':
put_object.cpp:(.text+0x4f4): undefined reference to `Aws::InitAPI(Aws::SDKOptions const&)'
put_object.cpp:(.text+0x6dc): undefined reference to `Aws::ShutdownAPI(Aws::SDKOptions const&)'
/tmp/cca4niF8.o: In function `Aws::Allocator<char>::allocate(unsigned long, void const*)':
put_object.cpp:(.text._ZN3Aws9AllocatorIcE8allocateEmPKv[_ZN3Aws9AllocatorIcE8allocateEmPKv]+0x23): undefined reference to `Aws::Malloc(char const*, unsigned long)'
/tmp/cca4niF8.o: In function `Aws::Allocator<char>::deallocate(char*, unsigned long)':
put_object.cpp:(.text._ZN3Aws9AllocatorIcE10deallocateEPcm[_ZN3Aws9AllocatorIcE10deallocateEPcm]+0x1c): undefined reference to `Aws::Free(void*)'
/tmp/cca4niF8.o: In function `Aws::Allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > > > >::deallocate(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > > >*, unsigned long)':
put_object.cpp:(.text._ZN3Aws9AllocatorISt13_Rb_tree_nodeISt4pairIKNSt7__cxx1112basic_stringIcSt11char_traitsIcENS0_IcEEEES8_EEE10deallocateEPSB_m[_ZN3Aws9AllocatorISt13_Rb_tree_nodeISt4pairIKNSt7__cxx1112basic_stringIcSt11char_traitsIcENS0_IcEEEES8_EEE10deallocateEPSB_m]+0x1c): undefined reference to `Aws::Free(void*)'
/tmp/cca4niF8.o: In function `Aws::Allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > > > >::allocate(unsigned long, void const*)':
put_object.cpp:(.text._ZN3Aws9AllocatorISt13_Rb_tree_nodeISt4pairIKNSt7__cxx1112basic_stringIcSt11char_traitsIcENS0_IcEEEES8_EEE8allocateEmPKv[_ZN3Aws9AllocatorISt13_Rb_tree_nodeISt4pairIKNSt7__cxx1112basic_stringIcSt11char_traitsIcENS0_IcEEEES8_EEE8allocateEmPKv]+0x30): undefined reference to `Aws::Malloc(char const*, unsigned long)'
/tmp/cca4niF8.o: In function `Aws::Allocator<std::_Sp_counted_ptr_inplace<std::basic_fstream<char, std::char_traits<char> >, Aws::Allocator<std::basic_fstream<char, std::char_traits<char> > >, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*)':
put_object.cpp:(.text._ZN3Aws9AllocatorISt23_Sp_counted_ptr_inplaceISt13basic_fstreamIcSt11char_traitsIcEENS0_IS5_EELN9__gnu_cxx12_Lock_policyE2EEE8allocateEmPKv[_ZN3Aws9AllocatorISt23_Sp_counted_ptr_inplaceISt13basic_fstreamIcSt11char_traitsIcEENS0_IS5_EELN9__gnu_cxx12_Lock_policyE2EEE8allocateEmPKv]+0x31): undefined reference to `Aws::Malloc(char const*, unsigned long)'
/tmp/cca4niF8.o: In function `Aws::Allocator<std::_Sp_counted_ptr_inplace<std::basic_fstream<char, std::char_traits<char> >, Aws::Allocator<std::basic_fstream<char, std::char_traits<char> > >, (__gnu_cxx::_Lock_policy)2> >::deallocate(std::_Sp_counted_ptr_inplace<std::basic_fstream<char, std::char_traits<char> >, Aws::Allocator<std::basic_fstream<char, std::char_traits<char> > >, (__gnu_cxx::_Lock_policy)2>*, unsigned long)':
put_object.cpp:(.text._ZN3Aws9AllocatorISt23_Sp_counted_ptr_inplaceISt13basic_fstreamIcSt11char_traitsIcEENS0_IS5_EELN9__gnu_cxx12_Lock_policyE2EEE10deallocateEPS9_m[_ZN3Aws9AllocatorISt23_Sp_counted_ptr_inplaceISt13basic_fstreamIcSt11char_traitsIcEENS0_IS5_EELN9__gnu_cxx12_Lock_policyE2EEE10deallocateEPS9_m]+0x1c): undefined reference to `Aws::Free(void*)'
/tmp/cca4niF8.o: In function `Aws::S3::Model::PutObjectRequest::~PutObjectRequest()':
put_object.cpp:(.text._ZN3Aws2S35Model16PutObjectRequestD2Ev[_ZN3Aws2S35Model16PutObjectRequestD5Ev]+0xf): undefined reference to `vtable for Aws::S3::Model::PutObjectRequest'
put_object.cpp:(.text._ZN3Aws2S35Model16PutObjectRequestD2Ev[_ZN3Aws2S35Model16PutObjectRequestD5Ev]+0x18a): undefined reference to `Aws::AmazonStreamingWebServiceRequest::~AmazonStreamingWebServiceRequest()'
collect2: error: ld returned 1 exit status

**Comment by KaibaLopez** [comment]
Hi @zcchai-iotex, 
So, this sounds to me more of a general linking issue you're having, rather than a problem specific to the sdk, so I'll be closing the issue.

Having said that though, don't want to just leave you hanging so... you seem to be trying to run the cpp file directly, this does not really link the libraries though, and so you get all these crazy errors. But, by running cmake and make, if done correctly, you've built an output file with the libraries properly linked, that output file is what you should be running.
(If you are following the getting started guide [here](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/getting-started.html) then run it as: `./my_example_project`)

hard to say if that's all you need to do without looking at your CMakeLists.txt files but hopefully this gets you a bit closer.
