### ISSUE TITLE
SDK Fails to compile on CentOS 7.5 and 7.6

### ISSUE THREAD

**Issue by shounak1** [aws/aws-sdk-cpp#1198]
### What platform/OS are you using?
Centos 7.5 and 7.6

### Which version of the SDK?
Tag - 1.7.144

### What compiler are you using? what version?
cmake 3.7.2

### What are your CMake arguments?
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" ..

### Can you provide a TRACE level log? (sanitize any sensitive information)
```
[ 20%] Built target aws-cpp-sdk-core
[ 20%] Building CXX object aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/source/S3Client.cpp.o
In file included from /root/aws-sdk-cpp/aws-cpp-sdk-s3/include/aws/s3/model/SelectObjectContentRequest.h:19:0,
                 from /root/aws-sdk-cpp/aws-cpp-sdk-s3/source/S3Client.cpp:114:
/root/aws-sdk-cpp/aws-cpp-sdk-s3/include/aws/s3/model/SelectObjectContentHandler.h:43:22: error: unused parameter ‘handler’ [-Werror=unused-parameter]
     class AWS_S3_API SelectObjectContentHandler : public Aws::Utils::Event::EventStreamHandler
                      ^
In file included from /root/aws-sdk-cpp/aws-cpp-sdk-s3/source/S3Client.cpp:114:0:
/root/aws-sdk-cpp/aws-cpp-sdk-s3/include/aws/s3/model/SelectObjectContentRequest.h: In member function ‘void Aws::S3::Model::SelectObjectContentRequest::SetEventStreamHandler(const Aws::S3::Model::SelectObjectContentHandler&)’:
/root/aws-sdk-cpp/aws-cpp-sdk-s3/include/aws/s3/model/SelectObjectContentRequest.h:82:92: note: synthesized method ‘Aws::S3::Model::SelectObjectContentHandler& Aws::S3::Model::SelectObjectContentHandler::operator=(const Aws::S3::Model::SelectObjectContentHandler&)’ first required here 
     inline void SetEventStreamHandler(const SelectObjectContentHandler& value) { m_handler = value; m_decoder.ResetEventStreamHandler(&m_handler); }
                                                                                            ^
	cc1plus: all warnings being treated as errors
make[2]: *** [aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/source/S3Client.cpp.o] Error 1
make[1]: *** [aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/all] Error 2
make: *** [all] Error 2
```
Hi guys I am facing the above issue while compiling the SDK on CentOS 7.5 and 7.6. I could successfully compile the same tag (1.7.144) on Ubuntu 14.04. Can someone please guide me with this issue.

**Comment by Leon-zsl** [comment]
same issue

**Comment by rturnbull1977** [comment]
same issue

**Comment by KaibaLopez** [comment]
Hi @shounak1, 
Could you tell us which compiler you're using?

**Comment by rturnbull1977** [comment]
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

**Comment by KaibaLopez** [comment]
Hi @rturnbull1977 , that's a sort of workaround you could go for depending on your application, and thanks for the instructions, but you're essentially turning off the warnings as errors flag, which is not the best approach. 
I'll try to narrow down the issue, but since it seems to be compiler related, it'd help a lot to know the OS and compiler versions in which this is happening.

**Comment by Leon-zsl** [comment]
In line 54 of file  SelectObjectContentHandler.h, Remove the unused parameter “handler” will make it work. And if you continue to compile, there are about 4 or 5 other “unused-parameter” issue, you can fix it like this. change SelectObjectContentHandler& operator=(const SelectObjectContentHandler& handler) = default; to SelectObjectContentHandler& operator=(const SelectObjectContentHandler&) = default;

**Comment by singku** [comment]
Gcc 4.8 doesn't have full c++ 11 features. I doubt that's a specific problem on CentOs 7.5/7.6 with old gcc.
Since https://en.cppreference.com/w/cpp/language/copy_assignment with default is a valid c++ 11 feature.
The lowest version of gcc we support is 4.9.4.
Would you mind updating gcc to a newer version and try that again?

**Comment by rturnbull1977** [comment]
Hello @KaibaLopez . Sorry for not getting back to you right away.  My current devel workstation is CentOS Linux release 7.6.1810 (Core).  In terms of the compiler, here are the packages I have installed ( gcc ):

gcc-4.8.5-36.el7_6.1.x86_64
gcc-c++-4.8.5-36.el7_6.1.x86_64
gcc-gfortran-4.8.5-36.el7_6.1.x86_64
libgcc-4.8.5-36.el7_6.1.x86_64

cmake:
cmake3-data-3.13.5-1.el7.noarch
cmake3-3.13.5-1.el7.x86_64

Looks like CentOS 7 package repositories might not have this version of gcc available ( packaged ).

**Comment by KaibaLopez** [comment]
Hi @rturnbull1977 , yes just as @singku mentioned in his comment, the problem is caused by the gcc version, and you're right, the centos dev packages only get you to version 4.8 so you'll have to install later gcc versions from source in order to run the sdk.
In my tests I updated gcc to 9.1 and that worked for me, try it out and let me know if you have more problems.

**Comment by rturnbull1977** [comment]
The company I work for will not allow source packages, so unless enterprise linux repositories don't have gcc 9, I cannot update.

You can close this ticket.

**Comment by shounak1** [comment]
Sorry for the late reply. I installed gcc 9.1 on my CentOS 7.5. However I ran into a few issues while compiling the SDK. So instead I removed the -Werror flag for a successful compilation. Will try out other gcc versions as soon as i get time.

**Comment by KaibaLopez** [comment]
Hi @shounak1, there are more dependencies that could give you problems if not updated, curl for example is one that I had to update outside the dev packages. But the error messages should be pretty clear about what's missing, give it a try and let me know how that goes.

**Comment by gaul** [comment]
It would be nice if the SDK supported older enterprise distros like RHEL 7 (GCC 4.8).  s3fs currently implements its own REST implementation which creates headaches with IAM and other features.  We still get bug reports for RHEL 6 which we don't support but there is a legacy constituency out there...
