### ISSUE TITLE
Error use of deleted function ‘Aws::Kinesis::KinesisClient on Ubuntu 16.04 and aws-sdk-cpp 1.3.21

### ISSUE THREAD

**Issue by dk1301** [aws/aws-sdk-cpp#757]
### What platform/OS are you using?
VM Ubuntu 16.04 x86_64

### What compiler are you using? what version?
g++ 5.4.0

### What's your CMake arguments?
 cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="config;core;kinesis"

### Can you provide a TRACE level log? (sanitize any sensitive information)
Build errors:
```
error: use of deleted function ‘Aws::Kinesis::KinesisClient::KinesisClient(const Aws::Kinesis::KinesisClient&)’

/usr/local/include/aws/kinesis/KinesisClient.h:182: error: use of deleted function ‘Aws::Client::AWSJsonClient::AWSJsonClient(const Aws::Client::AWSJsonClient&)’

/usr/local/include/aws/core/client/AWSClient.h:263: error: use of deleted function ‘Aws::Client::AWSClient::AWSClient(const Aws::Client::AWSClient&)’

/usr/local/include/aws/core/client/AWSClient.h:93: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = Aws::Auth::AWSAuthSignerProvider; _Dp = Aws::Deleter<Aws::Auth::AWSAuthSignerProvider>]’
```
Hi all, I have used the following code:

```
.....
SDKOptions options;
Aws::InitAPI(options);
  .                     
Aws::String accessToken = ....;
Aws::String sk = ....;
Aws::String skt = .....;

auto creds = Aws::Auth::AWSCredentials(accessToken, sk, skt);

Aws::Client::ClientConfiguration conf;
  
Aws::Kinesis::KinesisClient(creds, conf);
	
auto request = new Aws::Kinesis::Model::PutRecordRequest();
.......
```

The above code for Ubuntu 16.04, g++ 5.4.0, openSSL 1.0.2g, curl 7.47 and aws-sdk-cpp 1.2.22 is built correctly.

When I updated the aws-sdk-cpp to 1.3.21 the above errors occurred.
The same error with the 1.3.22 version.

Any ideas what is wrong?

**Comment by marcomagdy** [comment]
We added a unique_ptr to AWSClient which caused the copy ctor to be deleted.
What’s the reason you’re copying the Kinesis client?

**Comment by dk1301** [comment]
As a matter of fact I've created a KinesisClient function since I call it many times and in one point I set 
KinesisClient awsclient = my_function(arg1, arg2);
Should I change it ?

**Comment by marcomagdy** [comment]
No. This is my mistake, adding a unique_ptr member was a breaking change because it disallows copying. We'll have that reverted as soon as possible. Thanks for reporting this.

**Comment by singku** [comment]
This has been fixed in https://github.com/aws/aws-sdk-cpp/commit/9e1e8f14d3a10f6eabd71816556390a9f0ca7b37
