### ISSUE TITLE
build is failing because of assert added to StandardHttpRequest.cpp

### ISSUE THREAD

**Issue by david-koenig** [aws/aws-sdk-cpp#945]
### What platform/OS are you using?
Linux (using CodeBuild)

### Can you provide a TRACE level log? (sanitize any sensitive information)

Offending commit is here:
https://github.com/aws/aws-sdk-cpp/commit/111438a6b381a9ee4c261c51dcd408223b761773
aws-cpp-sdk-core/source/http/standard/StandardHttpRequest.cpp line 72

Here is output from our attempted build:

```
    /deps/aws-sdk-cpp/git/aws-cpp-sdk-core/source/http/standard/StandardHttpRequest.cpp: In member function 'virtual const String& Aws::Http::Standard::StandardHttpRequest::GetHeaderValue(const char*) const':
    /deps/aws-sdk-cpp/git/aws-cpp-sdk-core/source/http/standard/StandardHttpRequest.cpp:72:5: error: 'assert' was not declared in this scope
         assert (iter != headerMap.end());
         ^~~~~~
    /deps/aws-sdk-cpp/git/aws-cpp-sdk-core/source/http/standard/StandardHttpRequest.cpp:72:5: note: suggested alternative: 'tzset'
         assert (iter != headerMap.end());
         ^~~~~~
         tzset
    aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/build.make:513: recipe for target 'aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/http/standard/StandardHttpRequest.cpp.o' failed
```

**Comment by david-koenig** [comment]
Looks like this was fixed with https://github.com/aws/aws-sdk-cpp/pull/943

Please push that fix ASAP!

**Comment by singku** [comment]
Thanks for catching this issue, we have already had a fix but not yet pushed out, will update ASAP. Closing this issue first.
